### ISSUE TITLE
Build pipeline to intergrate vivarium backbone.

### ISSUE THREAD

**Issue by BenjaminIsaac0111** [BenjaminIsaac0111/daedalus#13]

**Comment by BenjaminIsaac0111** [comment]
- [ ] Couple new configuration methods with the old microsimulation.

- [ ] Get pipeline to run in a basic setup.

- [ ] Update documentation.

**Comment by kasra-hosseini** [comment]
Done, see: https://github.com/alan-turing-institute/daedalus
