### ISSUE TITLE
Get the Vivarium Public Health module installed and explore its functionallity.

### ISSUE THREAD

**Issue by BenjaminIsaac0111** [BenjaminIsaac0111/daedalus#9]

**Comment by BenjaminIsaac0111** [comment]
Need to investigate this method in add_new_birth_cohorts.py

```
def load_age_specific_fertility_rate_data(self, builder):
        asfr_data = builder.data.load("covariate.age_specific_fertility_rate.estimate")
        columns = ['year_start', 'year_end', 'age_start', 'age_end', 'mean_value']
        asfr_data = asfr_data.loc[asfr_data.sex == 'Female'][columns]
        return asfr_data
```

Not obvious where the asfr_data is coming from.

**Comment by BenjaminIsaac0111** [comment]
The asfr data in the tests are built and written in lines 154 and 155 of the test_add_new_birth_cohorts.py.

**Comment by crangelsmith** [comment]
Hi Wilson, have you added that test_add_new_birth_cohorts.py to the repo? It would be good to see how you implemented the test and data.
